apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosmos-api
  namespace: cosmos-app
spec:
  replicas: 2 # <--- MAGIC: K8s runs 2 copies automatically
  selector:
    matchLabels:
      app: cosmos-api
  template:
    metadata:
      labels:
        app: cosmos-api
    spec:
      containers:
        - name: node-app
          image: ghcr.io/sandeepsagarpanjala/cosmos-node-api:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: cosmos-secrets # We will create this from your .env
---
apiVersion: v1
kind: Service
metadata:
  name: cosmos-api-service
  namespace: cosmos-app
spec:
  selector:
    app: cosmos-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
