apiVersion: v1
kind: Service
metadata:
  name: cosmos-db-service
  namespace: cosmos-app
spec:
  type: LoadBalancer # 🏛️ Direct connection from your Mac to Postgres!
  ports:
    - port: 5433 # 📡 Port on your Mac
      targetPort: 5432 # 📦 Port inside the Pod
  selector:
    app: cosmos-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cosmos-db
  namespace: cosmos-app
spec:
  serviceName: "cosmos-db-service"
  replicas: 1 # Industry standard (one DB for consistency)
  selector:
    matchLabels:
      app: cosmos-db
  template:
    metadata:
      labels:
        app: cosmos-db
    spec:
      containers:
        - name: postgres
          image: postgres:alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_DB
              value: "Roadmap"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cosmos-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi # 💾 2GB Disk for your Cosmos data!
